version: '3.8'

services:
  db:
    container_name: "mysql-db"
    build:
      context: .
      dockerfile: db.Dockerfile
    networks:
      - mynet
    ports:
      - "3307:3306"
    restart: always
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "secret"
      MYSQL_ROOT_PASSWORD: "secret"
      MYSQL_DATABASE: "ledger"
      MYSQL_USER: "testuser"
      MYSQL_PASSWORD: "secret"
    volumes:
      - mysql-data:/var/lib/mysql
    cap_add:
    - SYS_NICE 
    command: --default-authentication-plugin=mysql_native_password

  server:
    container_name: "go-ledger"
    build:
      context: .
      dockerfile: server.Dockerfile
    ports:
      - 9000:9000
    depends_on: 
      - db
    volumes:
      - .:/app/
    networks:
      - mynet
networks:
  mynet:
    driver: bridge
volumes: 
  mysql-data:
